{% set name = "closure" %}
{% set version = "20191111" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a133ac625c55697645b1c41745e167572633982128ee7f06e401fd76cb4e292f

build:
  noarch: python
  number: 2
  entry_points:
    - closure = closure:main
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools
    - openjdk

test:
  requires:
    - python {{ python_min }}
  imports:
    - closure
  commands:
    - closure --help

about:
  home: http://pypi.python.org/pypi/closure
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Closure compiler packaged for Python
  doc_url: http://pypi.python.org/pypi/closure
  dev_url: https://github.com/miracle2k/python-closure

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - mwilson8
    - oblute
